# Generated by Django 4.0.6 on 2022-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MODERATOR', 'Модератор'), ('BASIC', 'Обычный пользователь')], default='BASIC', max_length=16, verbose_name='Роль'),
        ),
    ]
