# Generated by Django 4.0.6 on 2022-10-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme_status_alter_question_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='status',
            field=models.CharField(choices=[('ON_MODERATION', 'On moderation'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='ON_MODERATION', max_length=16, verbose_name='Статус'),
        ),
    ]
