# Generated by Django 4.0.6 on 2022-09-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_group',
            new_name='theme',
        ),
    ]
