# Generated by Django 4.0.6 on 2022-09-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_question_group_question_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
