# Generated by Django 4.0.6 on 2022-10-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
